name: Discord通知
description: ビルド結果などの詳細情報を Discord に通知

inputs:
  webhook_url:
    description: Discord Webhook URL
    required: true
  status:
    description: "ステータス（色選択用: start, success, failure）"
    required: true
  content:
    description: Discordメッセージ本文（Markdown形式）
    required: true
  username:
    description: Discordに表示するユーザー名
    required: false
    default: GitHub Actions

runs:
  using: 'composite'
  steps:
    # Discord通知を送信
    - name: 📢 Discord通知を送信
      run: |
        # ステータスに応じた色を設定
        case "${{ inputs.status }}" in
          start)
            COLOR="3447003"  # 青色
            ;;
          success)
            COLOR="3066993"  # 緑色
            ;;
          failure)
            COLOR="15158332"  # 赤色
            ;;
          *)
            COLOR="10181046"  # グレー色
            ;;
        esac

        # コミットメッセージの取得（最初の行のみ）
        COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s' 2>/dev/null || echo "N/A")

        # コミット者情報の取得
        COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an' 2>/dev/null || echo "N/A")

        # タイムスタンプ（ISO 8601形式）
        TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        # Discord Webhook用のJSONペイロード
        # jqを使って安全にJSON生成
        PAYLOAD=$(jq -n \
          --arg username "${{ inputs.username }}" \
          --arg content "${{ inputs.content }}" \
          --argjson color "${COLOR}" \
          --arg repo "${{ github.repository }}" \
          --arg branch "${{ github.ref_name }}" \
          --arg sha "${{ github.sha }}" \
          --arg short_sha "${GITHUB_SHA:0:7}" \
          --arg commit_url "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" \
          --arg actor "${{ github.actor }}" \
          --arg workflow "${{ github.workflow }}" \
          --arg run_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          --arg timestamp "${TIMESTAMP}" \
          --arg commit_msg "${COMMIT_MESSAGE}" \
          --arg commit_author "${COMMIT_AUTHOR}" \
          '{
            username: $username,
            content: $content,
            embeds: [{
              color: $color,
              fields: [
                {
                  name: "🌿 ブランチ",
                  value: $branch,
                  inline: true
                },
                {
                  name: "👤 実行者",
                  value: $actor,
                  inline: true
                },
                {
                  name: "📝 コミット",
                  value: ("[\($short_sha)](\($commit_url))"),
                  inline: true
                },
                {
                  name: "✍️ コミット者",
                  value: $commit_author,
                  inline: true
                },
                {
                  name: "🔗 ワークフロー",
                  value: ("[\($workflow)](\($run_url))"),
                  inline: true
                },
                {
                  name: "🕒 更新日時",
                  value: $timestamp,
                  inline: true
                },
                {
                  name: "💬 コミットメッセージ",
                  value: $commit_msg
                }
              ]
            }]
          }')

        # Discord Webhookに送信
        if [ -n "${{ inputs.webhook_url }}" ]; then
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Content-Type: application/json" \
            -d "${PAYLOAD}" \
            "${{ inputs.webhook_url }}")

          if [ "$HTTP_STATUS" -eq 204 ]; then
            echo "✅ Discord通知を送信しました（Status: ${HTTP_STATUS}）"
          else
            echo "⚠️ Discord通知の送信に失敗しました（Status: ${HTTP_STATUS}）"
          fi
        else
          echo "⚠️ Discord Webhook URLが設定されていません"
        fi
      shell: bash